os: Visual Studio 2015
install:
  - Webpicmd /install /products:"MicrosoftAzure-ServiceFabric" /AcceptEULA
  - cmd: SET PATH=%PATH%;C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code;C:\Program Files\Microsoft SDKs\Service Fabric\Tools\ServiceFabricLocalClusterManager
  - ps: Restart-Computer -Force
  - ps: Start-Sleep -s 10
build_script:
  - ps: Import-module ServiceFabric
  - ps: Get-Command Test-ServiceFabricApplicationPackage | fl *
  - dir C:\windows\system32\windowspowershell\v1.0\Modules\ServiceFabric
  - powershell .\test.ps1

on_finish:
- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
